### ISSUE TITLE
Ошибки в грамматике

### ISSUE THREAD

**Issue by wwall** [1c-syntax/intellij-language-1c-bsl#14]
Замеченые ошибки - 

Код на 1С допускает такое

#Если Сервер тогда
Функция х()
#иначе 
Процедура у()
#конецесли

Дополнитеотно можно так 
Процедура х(у 
	#Если Сервер тогда 
		,z 
#конецесли
)	
КонецПроцедуры

нет поддержки ДобавитьОбработчик /УдалитьОбработчик/перейти

Область и препроцессор  - не часть грамматики. Это отдельный процесс. 

Возможно такое объявление строки 
ЭтоСтрокаСперносом = "Это строка " "с переносом"

поддержка Новый - возможно использовать так 
ИмяТипа = Новый ("ТаблицаЗначений");

определение параметра по умолчанию может быть таким - 
Функция х(у = +1) 
Или 
Функция х(у = -1) 

Кстати, плюс может быть использован так 
х = 1 ++  2;

**Comment by nixel2007** [comment]
Спасибо, @wwall!
Мы далеки от релиза, грамматика только вырабатывается.

В плане препроцессора - да, я понимаю. С ним вообще очень много сложностей в любых языках. На данный момент для простоты препроцессор введён в аст, с соответствующими ограничениями, однако в будущем я хочу строить отдельные контекстное деревья. Но это пока далеко.

**Comment by nixel2007** [comment]
@wwall ДобавитьОбработчик /УдалитьОбработчик/Перейти (а так же саму метку и Прервать) добавил.

Вопрос - что тебя не устроило в поддержке Новый?

![image](https://user-images.githubusercontent.com/1132840/50447798-43bcef80-0950-11e9-97dd-be66973df5e3.png)

Или не нравится, что можно в качестве типа передать явную строку, вместо переменной или вызова функции? Если да, то я не уверен, что эта ошибка должна кидаться парсером, а не интерпретатором =/

**Comment by wwall** [comment]
ТЗ = новый("ТаблицаЗначений") это не ошибка, а вполне себе нормаьлное поведение. 
Сейчакс под рукой нет 1С, но такое помоему тоже можно
ТЗ = новый(ФункцияВозвращающаяТипИлиСтроку());

У тебя парсер отвалится на таком, а 1С вполне себе выполнит.

**Comment by nixel2007** [comment]
@wwall 

![image](https://user-images.githubusercontent.com/1132840/50449180-2855e280-0958-11e9-8658-a979ecee5fed.png)

Работает.

**Comment by wwall** [comment]
ТЗ = новый("Таблица"+ФункцияВозвращающаяСловоЗачений());

Идея в том что аргумент у Новый - это выражение а не вызов функции.

**Comment by wwall** [comment]
для первать такой код должен быть некоректным
Функция х()
 Прервать;
Конецфункции

у тебя же пройдет разбор.

**Comment by nixel2007** [comment]
> ТЗ = новый("Таблица"+ФункцияВозвращающаяСловоЗачений());
Идея в том что аргумент у Новый - это выражение а не вызов функции.

Если там выражение, то оно матчится на expression:

![image](https://user-images.githubusercontent.com/1132840/50449412-d6ae5780-0959-11e9-866b-cfc303fed71b.png)

**Comment by nixel2007** [comment]
> для первать такой код должен быть некоректным
Функция х()
Прервать;
Конецфункции

вот на это я пожалуй отдельную задачку повешу. я пока хз, как это красиво обернуть в файле грамматики, скорее всего нужно писать доп. перехватчик на это дело.

**Comment by wwall** [comment]
сделай как в ecmascripte - разный набор codeblocs в зависиомсти от конструкций.

**Comment by wwall** [comment]
> > ТЗ = новый("Таблица"+ФункцияВозвращающаяСловоЗачений());
> > Идея в том что аргумент у Новый - это выражение а не вызов функции.
> 
> Если там выражение, то оно матчится на expression:
> 
> ![image](https://user-images.githubusercontent.com/1132840/50449412-d6ae5780-0959-11e9-866b-cfc303fed71b.png)
Ага, не заметил продолжения.
